/* to string */
let num1 = 17;
console.log('17 to string is ' + String(17));
let num2 = -17.17;
console.log('-17.17 to string is ' + String(-17.17));
let bool1 = false;
let boolStr = String(false)
console.log('false to string is ' + boolStr);
let something = null;
console.log('null to string is ' + String(null));
let somethingElse = undefined;
console.log('undefined to string is ' + String(undefined));
let zerro = 0;
let zerroStr = String(zerro);
console.log('0 to string is ' + zerroStr);

/* to number */
let numb1 = "17";
console.log("'17' to number is " + Number(numb1));
console.log('true to number is ' + Number(true));
console.log('false to number is ' + Number(false));
let nothing = null;
console.log('null to number is ' + Number(nothing));
// console.log('undefined to number is ' + Number(undefine));
console.log("'   20   ' to number is " + Number('   20   '));
console.log("'      ' to number is " + Number('      '));
console.log("'   30d   ' to number is " + Number('   30d   '));
console.log("Task 2_____________________________________");
const a = 17;
const b = 5;
console.log(1);
console.log(a > b);
console.log(a <= b);
console.log(a == b);
console.log(a != b);
console.log(2);
console.log('a' < 'b');
console.log('ab' > 'a');
console.log('17' > 1);
console.log(3);
console.log(17 === 1);
console.log(17 === 17);
console.log(17 === '17');
console.log(17 === true);
console.log(4);
console.log('0' === '');
console.log(5);
console.log(true === false);
console.log(true === true);
console.log(null === undefined);
console.log(false === 0);
console.log(6);
console.log(17 == '17');
console.log('0' == '');
console.log(0 == '');
console.log(7);
console.log(null == undefined);
console.log(false == 0);
console.log(8);
console.log(undefined == null);
console.log(undefined == 0);
console.log(null == 0);
console.log(undefined < 0);
console.log(undefined > 0);